import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { ApiError } from '@/api/client';
import { endpoints } from '@/api/endpoints';
import { Card, PrimaryButton, shared } from '@/components/Card';
import { Loading, Message } from '@/components/States';
import { callLead, whatsappLead } from '@/services/contact';
import { colors, stages } from '@/theme';
import type { Lead, User } from '@/types/models';
export default function LeadDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [lead, setLead] = useState<Lead>(); const [users, setUsers] = useState<User[]>([]); const [assignmentAvailable, setAssignmentAvailable] = useState(true); const [note, setNote] = useState(''); const [followUp, setFollowUp] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = async () => { setError(''); try { const result = await endpoints.lead(id); setLead(result.data); setFollowUp(result.data.followUpAt || ''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load lead'); } };
  // Reload when the route identity changes; load is intentionally local to this screen render.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); endpoints.users().then(r => setUsers(r.data)).catch(e => { if (e instanceof ApiError && [403, 404, 501].includes(e.status)) setAssignmentAvailable(false); else setAssignmentAvailable(false); }); }, [id]);
  const action = async (work: () => Promise<unknown>, success: string) => { setBusy(true); try { await work(); await load(); Alert.alert('Done', success); } catch (e) { Alert.alert('Unable to update lead', e instanceof Error ? e.message : 'Try again.'); } finally { setBusy(false); } };
  if (!lead && !error) return <Loading />; if (!lead) return <Message text={error} retry={load} />;
  const name = `${lead.contact?.firstName || ''} ${lead.contact?.lastName || ''}`.trim() || 'Unnamed lead';
  return <ScrollView style={shared.screen} contentContainerStyle={shared.content}><Text style={shared.title}>{name}</Text><Text style={shared.subtitle}>{lead.contact?.company || 'No company'} · Score {lead.score ?? '—'}</Text><Card><Text style={shared.label}>Contact</Text><Text>{lead.contact?.phone || 'No phone'}</Text><Text>{lead.contact?.email || 'No email'}</Text>{lead.contact?.phone && <View style={shared.row}><PrimaryButton title="Call" onPress={() => void callLead(lead.contact?.phone!, lead._id)} /><PrimaryButton title="WhatsApp" onPress={() => void whatsappLead(lead.contact?.phone!).catch(e => Alert.alert('Unavailable', e.message))} /></View>}</Card><Card><Text style={shared.label}>Stage</Text><View style={s.wrap}>{stages.map(stage => <Pressable disabled={busy} key={stage} style={[s.chip, lead.stage === stage && s.active]} onPress={() => action(() => endpoints.updateLead(id, { stage }), 'Stage updated.')}><Text style={lead.stage === stage ? s.activeText : undefined}>{stage}</Text></Pressable>)}</View></Card><Card><Text style={shared.label}>Schedule follow-up</Text><TextInput style={shared.input} value={followUp} onChangeText={setFollowUp} placeholder="2026-08-01T10:30:00.000Z" autoCapitalize="none" /><PrimaryButton disabled={busy || Boolean(followUp && Number.isNaN(Date.parse(followUp)))} title="Save follow-up" onPress={() => action(() => endpoints.updateLead(id, { followUpAt: followUp ? new Date(followUp).toISOString() : undefined }), 'Follow-up scheduled.')} /></Card><Card><Text style={shared.label}>Add note</Text><TextInput style={[shared.input, s.note]} multiline value={note} onChangeText={setNote} placeholder="Conversation details…" /><PrimaryButton disabled={busy || !note.trim()} title="Add note" onPress={() => action(async () => { await endpoints.addNote(id, note.trim()); setNote(''); }, 'Note added.')} /></Card><Card><Text style={shared.label}>Assignment</Text>{!assignmentAvailable ? <Text style={shared.subtitle}>Assignment is unavailable for this account or API deployment.</Text> : users.length ? users.map(user => <Pressable key={user._id} disabled={busy} style={s.user} onPress={() => action(() => endpoints.assign(id, user._id), `Assigned to ${user.name || user.email}.`)}><Text>{user.name || user.email}</Text></Pressable>) : <Text style={shared.subtitle}>No assignable users returned.</Text>}</Card></ScrollView>;
}
const s = StyleSheet.create({ wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderWidth: 1, borderColor: colors.border, borderRadius: 18, paddingHorizontal: 12, paddingVertical: 7 }, active: { backgroundColor: colors.primary, borderColor: colors.primary }, activeText: { color: 'white' }, note: { minHeight: 90, textAlignVertical: 'top' }, user: { paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.border } });
